OPENAI_API_KEY = "your-openai-api-key"
SF_CLIENT_ID = "your-salesforce-consumer-key"
SF_CLIENT_SECRET = "your-salesforce-consumer-secret"
SF_USERNAME = "your-salesforce-username@example.com"
SF_PASSWORD = "your-salesforce-password"
SF_SECURITY_TOKEN = "your-salesforce-security-token"
SF_DOMAIN = "login"
